# Generated by Django 4.0.2 on 2022-02-22 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
