# Generated by Django 4.0.2 on 2022-02-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_phone_num_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(' ', "Regular- Can't delete members"), ('Admin', 'Admin- Can delete members')], max_length=50),
        ),
    ]
